### ISSUE TITLE
Please label 1.16 version as deprecated or fix the network bug on that version

### ISSUE THREAD

**Issue by sharpskull2** [starforcraft/Botany-Pots-Tiers#10]
Please fix this issue on 1.16, or label the 1.16 version of this mod as deprecated.
this isn't just a small bug that would fly under the radar most of the time. This is a fairly game/server crippling bug that can make the game unplayable for anyone that isn't on the same network as the server.

Lots of packs that would make use of this mod are going to make use of them in large quantities, and in doing so are going to cause problems for anyone playing on a server with friends or other people. You can't just expect everyone to go to 1.18 when there are plenty of packs that are still being developed or released for 1.16 

again, please look into fixing this bug, or at least say on the mod page that the 1.16 version is deprecated and should no longer be used

_Originally posted by @sharpskull2 in https://github.com/starforcraft/Botany-Pots-Tiers/issues/5#issuecomment-1297645791_

**Comment by starforcraft** [comment]
I don't think that the lag spikes are caused by this mod because as you can see on the pictures above in #5, Spark is saying that botany pots tiers only takes up 0.9% of the performance.

**Comment by sharpskull2** [comment]
From experience using this mod with friends on a server, I can without a doubt say it is this mod. Having them around our base we were getting network spikes fairly irregularly. As soon as we added more around our base we were getting constant network lag and getting timed out from the server. Keep in mind during that whole time TPS was steady at 20, but our ping to the server was in the several thousands to 10s of thousands. As soon as we removed the tiered pots from around our base the network lag disappeared entirely. 

but please go ahead and test the mod on your own, or you can label the 1.16 version as deprecated to be safe so that modpack authors do not use the mod in their packs
