### ISSUE TITLE
[1.19.2] Tube Coral doesn't grow properly

### ISSUE THREAD

**Issue by HalcyonSeas73** [starforcraft/Botany-Pots-Tiers#11]
Minecraft version: 1.19.2
Forge version: 43.1.47
BotanyPots version: 9.0.11
BotanyPots Tiers version: 3.0.1.0

Tube Coral, grown in a Creative Hopper Botany Pot, does not grow at the same speed as the other corals; in fact, the speed boost doesn't seem to be applying properly at all.

**Comment by starforcraft** [comment]
https://user-images.githubusercontent.com/60074805/201512307-4d903e20-42be-4af8-97a0-dc8adf471d75.mp4

**Comment by HalcyonSeas73** [comment]
Yes, the Tube Coral Fan works; the 'tall' Tube Coral will go for a few cycles properly, but then stops.
https://imgur.com/a/nSCub5m

**Comment by starforcraft** [comment]
https://streamable.com/swdawu
