### ISSUE TITLE
[1.19.2] Tube Coral Part 2: Now with more evidence

### ISSUE THREAD

**Issue by HalcyonSeas73** [starforcraft/Botany-Pots-Tiers#12]
Minecraft version: 1.19.2
Forge version: 43.1.47
BotanyPots version: 9.0.11
BotanyPots Tiers version: 3.0.1.0

Not sure if you saw the comment I made on the closed issue #11 ;
Tube Coral, grown in a Creative Hopper Botany Pot, does not grow at the same speed as the other corals; in fact, the speed boost doesn't seem to be applying properly at all.

Yes, the Tube Coral Fan works; the 'tall' Tube Coral will go for a few cycles properly, but then stops.
[Imgur-hosted GIF of the [lack of] process](https://imgur.com/a/nSCub5m)

**Comment by starforcraft** [comment]
I saw it
