### ISSUE TITLE
[1.19.2] Updates to Botany Pots

### ISSUE THREAD

**Issue by HalcyonSeas73** [starforcraft/Botany-Pots-Tiers#13]
Minecraft version: 1.19.2
Forge version: 43.1.55
BotanyPots version: 9.0.13
BotanyPots Tiers version: 3.0.1.0

Botany Pots has made lots of updates to compatibility with other mods, including more support for different trees via Botany Trees. There is also partial Farmer's Delight support. Requesting Botany Pots Tiers updates for parity.

**Comment by starforcraft** [comment]
I don't want/have the time to make updates only to add new mod supports. You can add them yourself with for example "botanypotstiers:crop" or "botanypotstiers:soil". Before the rewrite (in 1.16.5) every soil and crop from botany pots got "moved" over to botany pots tiers, but that is not possible now. I am still trying to find a solution and if I do I will bring a new update out.
