### ISSUE TITLE
Additional drops never happen

### ISSUE THREAD

**Issue by benbenlaw** [starforcraft/Botany-Pots-Tiers#15]
![image](https://user-images.githubusercontent.com/42780877/211158956-784153b0-8e41-40d6-be36-1d52b210bcff.png)

This recipe producing wheat and seeds (at a chance) in normal botany pots the seeds have a chance to drop and do

When inside a tiered pot the addtional product is never made

**Comment by benbenlaw** [comment]
![image](https://user-images.githubusercontent.com/42780877/211158990-371cce41-59da-4f4b-a013-c28193e75c46.png)
ultra pot

**Comment by starforcraft** [comment]
Either you are unlucky or this is a bug in the base mod. The Tiered Pots also don't increase the drop chance

**Comment by benbenlaw** [comment]
the seeds are dropping in the normal botany pots

**Comment by benbenlaw** [comment]
![image](https://user-images.githubusercontent.com/42780877/211161504-a5449dba-4f49-41d8-af00-4e159d0a9acd.png)

**Comment by benbenlaw** [comment]
![image](https://user-images.githubusercontent.com/42780877/211161721-1d875adc-fcbd-457e-8a20-a10fe3586d14.png)

i dont think its a case of bad luck

**Comment by benbenlaw** [comment]
having a item with a 1.00 chance does generate the item, i think theres a problem with the maths in this mod as anything less doesnt work

**Comment by starforcraft** [comment]
You were right, thanks for the report! https://www.curseforge.com/minecraft/mc-mods/botany-pots-tiers/files/4314679

**Comment by benbenlaw** [comment]
awesome thank you for the quick responce :) and it works now
