### ISSUE TITLE
Tier Elite+ not compatible with Harvestcraft/BYG

### ISSUE THREAD

**Issue by LarcekGiglamesh** [starforcraft/Botany-Pots-Tiers#18]
using:
• Forge 1.18.2 - 40.2.1
• BotanyPots-Forge-1.18.2-8.0.24
• BotanyTrees-Forge-1.18.2-4.0.6
• BotanyPotsTiers-Forge-1.18.2-2.1.2
• Oh_The_Biomes_You'll_Go-forge-1.18.2-1.4.7
• pamhc2crops-1.18.2-1.0.5
• pamhc2trees-1.18.2-1.0.4
( • pamhc2foodcore-1.18.2-1.0.3 )
( • pamhc2foodextended-1.18.2-1.0.5 )

Issue:
a Harvestcraft Tree such as the Walnut Tree is able to grow and transmit its harvest using the basic Tier "Hopper Botany Pot" towards the connected Storage, but once upgraded to "Elite Hopper Botany Pot" it looses the ability to use such trees. Vanilla Trees and Seeds are still able to produce, but neither Trees from BYG nor Harvestcraft

cheers

**Comment by starforcraft** [comment]
You have to add the recipes yourself. (Or update to 1.19.2 or 1.19.3 because in these versions the recipes get synced over to this mod. A backport isn't possible because a code had to be changed to make this possible https://github.com/Darkhax-Minecraft/BotanyPots/commit/211198cc5e1b4be9ed1804bfa405060fcee9f78a)

**Comment by LarcekGiglamesh** [comment]
thanks for the response. too bad, there seemed to have even a pull request to fix this. could you at least share a working recipe as an example to get started on this for 1.18.2 then? 

i don't see a config option for Botany-Pots-Tiers to define them, neither do i see a Wiki here to reference CraftingRecipes API whether that'd be for CraftTweaker or KubeJS, also haven't found one on the discord, so one example would be a huge help.

**Comment by starforcraft** [comment]
https://www.curseforge.com/minecraft/mc-mods/botany-pots-tiers/files/4394900
