### ISSUE TITLE
Stop adding non-basic pots to Botany’s basic pot tag

### ISSUE THREAD

**Issue by TelepathicGrunt** [starforcraft/Botany-Pots-Tiers#19]
I’m the dev of Bumblezone and I have a mob that can randomize the colors of some items when given. I used the Botany Post’s basic pot tag so that giving a basic pot gives a random different color basic pot.

This tier mod is adding all sorts of random non-basic pots into the tag and breaking the balance with my mod and possibly others that are relying on the basic pot tag to be only basic pots. My suggestion is remove all the tier pots out of the basic pot tag. Both item and block tag

This the the problematic tag: https://github.com/starforcraft/Botany-Pots-Tiers/blob/main/Common/src/main/resources/data/botanypots/tags/items/basic_botany_pots.json

issue report I got because of the tag: https://github.com/TelepathicGrunt/Bumblezone/issues/227

**Comment by starforcraft** [comment]
Sorry I didn't think something like this could happen. I am changing it now immediately

**Comment by TelepathicGrunt** [comment]
Awesome, thank you!

**Comment by P3rf3ctXZer0** [comment]
I want an option to toggle please. Don't drastically change the mod and not allow a toggle I like things as they are.

**Comment by TelepathicGrunt** [comment]
@P3rf3ctXZer0 It’s a tag that you can add the pots you want back in. The point of tags is it is customizable and pack makers like you can add whatever you want to it by datapack or kubejs or craftweaker. There’s no point to a toggle because the tag itself is already customizable 

By default, the special pots are not basic pots so they did not belong in the tag. You can grab the original tag files from this commit and add it to your datapack by the methods I specified above. 
https://github.com/starforcraft/Botany-Pots-Tiers/commit/7728608d1197749265ac0f31a6160dab6b048399

if you don’t know how to add tags to your modpack to ship out to others, you should check out kubejs and crafttweaker wiki and discord to get help or brush up on how to make datapacks and ship it with your modpack by using mods like Global Packs or Paxi to make the datapack apply to all worlds

**Comment by P3rf3ctXZer0** [comment]
I cannot code ... I can use clearly written data packs ... due to disability I have trouble processing strings and long code with wild card variables. If you want to make a data pack I will just add that to my pack.

**Comment by TelepathicGrunt** [comment]
All I did was just copy/paste the commit's content I linked into a blank datapack.
[BotanyPotTiersTagging.zip](https://github.com/starforcraft/Botany-Pots-Tiers/files/11084742/BotanyPotTiersTagging.zip)
