### ISSUE TITLE
Pots not all working

### ISSUE THREAD

**Issue by MrStatman80** [starforcraft/Botany-Pots-Tiers#2]
I'm playing with this mod and some of the pots doesn't work all the time as you need to break them to reset it

The link below is proof of what is happening

https://www.youtube.com/watch?v=h30t5VlNbsI

**Comment by starforcraft** [comment]
Uhh I think you are on the wrong Github Project lol

**Comment by starforcraft** [comment]
Oh wait nvm you just send the wrong link xD

**Comment by starforcraft** [comment]
Could you send your log?

**Comment by starforcraft** [comment]
(And can I ask how you got Avaritia in that pack?)

**Comment by starforcraft** [comment]
Log and Crash Report is something completely different

**Comment by MrStatman80** [comment]
I have used all your mods for upgrades from Refined to the Bees... And all are great.. just this one is causing issues

But how do I find my log files?

**Comment by MrStatman80** [comment]
so it's called .log.gz?

**Comment by starforcraft** [comment]
No that are old log files latest.log is the latest one

**Comment by MrStatman80** [comment]
Request is too large for pastebin

**Comment by starforcraft** [comment]
I think this issue is fixed in 1.18.2 and up
