### ISSUE TITLE
I think the config keeps resetting itself.

### ISSUE THREAD

**Issue by YassaaaTU** [starforcraft/Botany-Pots-Tiers#20]
I am using the latest version for 1.19.2 and I changed the values for pot speed and multiplier but when I come to check on them again I see that they are reset to default.

**Comment by starforcraft** [comment]
Did you close the game before changing the configs?

**Comment by YassaaaTU** [comment]
Yea I did. 
But now for some reason it looks like this: 
![image](https://github.com/starforcraft/Botany-Pots-Tiers/assets/5587106/4af525e6-5aac-4037-863c-d1bdee43bd6f)

when it was first generated it looked like this:
![image](https://github.com/starforcraft/Botany-Pots-Tiers/assets/5587106/87005bc7-7f29-4f0f-9464-8554585b2e0d)

but it works so im not complaining :)
