### ISSUE TITLE
Fix datapack

### ISSUE THREAD

**Issue by HuanGeiWoLiuGeBi** [starforcraft/Botany-Pots-Tiers#22]
**Fabric 1.18.2**
data/botanypotstiers/recipes/immersiveengineering/crop/hemp.json
[This is fabric not forge, fabric donot support forge special load condition api]
should change its content to:

**{"type":"botanypotstiers:crop","bookshelf:load_conditions":[{"type":"bookshelf:item_exists","values":["immersiveengineering:seed","immersiveengineering:hemp_fiber"]}],"seed":{"item":"immersiveengineering:seed"},"categories":["dirt"],"growthTicks":1600,"display":[{"block":"immersiveengineering:hemp","properties":{"growth":"bottom4"}},{"block":"immersiveengineering:hemp","properties":{"growth":"top0"}}],"drops":[{"chance":1.0,"output":{"item":"immersiveengineering:hemp_fiber"},"minRolls":1,"maxRolls":3},{"chance":0.05,"output":{"item":"immersiveengineering:seed"},"minRolls":1,"maxRolls":2}]}**

**Comment by starforcraft** [comment]
Sorry, but I don't support 1.18.2 anymore
