### ISSUE TITLE
1.19.2 version 3.3.2 would not work

### ISSUE THREAD

**Issue by InsaneInsomniac** [starforcraft/Botany-Pots-Tiers#23]
just started playing all the mods 8, tried to add this as a qol upgrade since I don't have a server to let the game idle while I'm not playing. version 3.3.2 would not even register as being added to the pack, no errors related to it, didn't show up in loaded mods list, items didn't show up in game. nothing. reloaded, nothing. removed and redownloaded. nothing. downgraded to version 3.3.1 and that works perfectly fine so far. gonna just stick with that but figured I should let ya know 3.3.2 failed hard.

**Comment by starforcraft** [comment]
Closing this as there is no further information
