### ISSUE TITLE
Incompatibility with some corals and other mod items

### ISSUE THREAD

**Issue by Mourdida** [starforcraft/Botany-Pots-Tiers#26]
In the modpack Ragnamod VII, Tube Coral Blocks and Tube Coral Fans can grow in Hopper Botany Pots of BotanyPotsTiers, but sometimes don't produce anything when fully grown and just stop growing after a few cycles.

Moreover, Brain Coral Fans can grow in normal Botany Pots but not in the Botany Pots of BotanyPotsTiers (they'not recognized as a seed item). The same issue was identified with Dullthorns and Luminous Fungus from the mod Infernal Expansion.

The author of the modpack identified the issues, which he corrected. Here's the link to the git bug report, with the commit from the author to correct the issues : https://github.com/MLDEG/Ragnamod_VII/issues/65#issue-2127548493

**Comment by starforcraft** [comment]
1.18.2 is no longer supported. But in 1.19.2 and above, recipes from botany pots are automatically synchronized
