### ISSUE TITLE
[Requested Feature]: Hopper pots upgrade recipes.

### ISSUE THREAD

**Issue by NightOps007** [starforcraft/Botany-Pots-Tiers#3]
I think most people immediately make hopper pots as soon as possible. Could you add the recipes for upgrading hopper pots to the next tier?

**Comment by MaryKirschner** [comment]
agreed

**Comment by starforcraft** [comment]
https://www.curseforge.com/minecraft/mc-mods/botany-pots-tiers/files/3769883

**Comment by starforcraft** [comment]
Only took about 5 months xD
