### ISSUE TITLE
Add Pots to "machine" in JEI

### ISSUE THREAD

**Issue by AFKafe** [starforcraft/Botany-Pots-Tiers#33]
Greetings,

I'm a pack developer and I just realized that your mod doesn't add the higher tier pots to the JEI crafts page. So when we do "U" on one of the pots it does not show us the seeds that can be planted in it. (Example in the short video)
![BotanyPotsTiers](https://github.com/user-attachments/assets/5d8c2747-b7ac-43c1-8362-ade5ba5dd60f)

Do you know if it is possible to add the pots to the "machines" list ?

Thanks in advance
AFKafé

**Comment by AFKafe** [comment]
For more information, I'm on the 1.20.1-6.0.1 version.

**Comment by starforcraft** [comment]
https://legacy.curseforge.com/minecraft/mc-mods/botany-pots-tiers/files/5953202
