### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by Darkhax** [starforcraft/Botany-Pots-Tiers#4]
Hello, I am the author of Botany Pots. 

After looking through your source code, nearly all of it seems to be a verbatim copy of the original Botany Pots code with a few minor tweaks to allow for your tier system. The original code is licensed under LGPL v2.1 which allows for modification and redistribution, however it does not allow for sublicensing which you have done.

Please review the LGPL v2.1 license and make the necessary changes. I have no issue with this addon or others existing, however you need to follow the license if you're going to reuse a significant amount of the code. 

Thanks

**Comment by starforcraft** [comment]
Oh sorry! I completely forgot to change the License on Github, I will change it immediately.
