### ISSUE TITLE
Large amounts of pots cause player timeouts and large network spikes

### ISSUE THREAD

**Issue by DatenThielt** [starforcraft/Botany-Pots-Tiers#5]
After spending 3 hours debugging a local server that I run for a friend of mine we found that this mod was causing an issue spesific to his player.
 
Mod Version: 1.141
MC Version:  1.16.5

We had roughly 150 pots of the first tier out in a sky-block mod-pack (Project Isothermal Expert).  40ish were filled with dirt and seeds.  100ish had just dirt and 10 had nothing.  The dirt used was Supremium.

When the player logged in his ping would start slowly rising.  until it got to 2000ish and it timed him out.  

After removing all the pots his ping would return to normal. 

I'm not sure if its the empty pots, pots with dirt or just the sheer amount of pots that is causing the issue but it is 100% this mod.  placing out 150 normal botany pots does not cause the same issue,  I understand these are faster but they should not cause a timeout or ping to rise. 

If you need any additional information please let me know.

**Comment by starforcraft** [comment]
Can you maybe run spark?

**Comment by DatenThielt** [comment]
I've never used spark before but I can give it a go for sure,  The odd part was that it was only happening to the one player who was not local to the server , making it seem somewhat network related.  But once I figure out spark I will let you know

**Comment by DatenThielt** [comment]
I'm not super sure if this is what you need but this is a profiler run without that player being on, but the 150 pots present as described above

https://spark.lucko.me/LVOq17YW6O

**Comment by DatenThielt** [comment]
And this profiler is from when he is on the server

https://spark.lucko.me/q4nDa80QSy

**Comment by DatenThielt** [comment]
and finally this is with the pots removed

https://spark.lucko.me/EYfrIv4JxN

**Comment by starforcraft** [comment]
Did you take that picture when it wasn't lagging yet?

**Comment by DatenThielt** [comment]
The first and second profile were taken when the pots were in world,  This is only causing the other players ping to go up to 2000-4000.  The server itself is still performing fine for myself and TPS/other mods are running fine

The final picture is taken with the pots removed,  My friends ping drops down to 70ish at this point.  I dont know if there is a network profiler included with spark?

**Comment by starforcraft** [comment]
Ah okay, so its a client side issue. Can you maybe send a screenshot with [Observable](https://www.curseforge.com/minecraft/mc-mods/observable) mod?

**Comment by DatenThielt** [comment]
It appears I cannot get Observable to load on either the server or the client I am afraid,  Are there any other tools that could be used?

**Comment by starforcraft** [comment]
I think this issue is fixed in 1.18.2 and up so I am going to close this issue
